//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThienLongBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThamDo
    {
        public int maCH { get; set; }
        public int stt { get; set; }
        public string noiDungTraLoi { get; set; }
        public Nullable<int> soLanBinhChon { get; set; }
    
        public virtual ThamDo ThamDo { get; set; }
    }
}
