//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThienLongBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public string maGH { get; set; }
        public Nullable<int> maSach { get; set; }
        public string tenSach { get; set; }
        public string anhBia { get; set; }
        public Nullable<decimal> donGia { get; set; }
        public Nullable<int> soLuong { get; set; }
        public string maCD { get; set; }
        public Nullable<decimal> thanhToan { get; set; }
    }
}
