//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThienLongBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public int stt { get; set; }
        public string tenCongTy { get; set; }
        public string hinhMinhHoa { get; set; }
        public string href { get; set; }
        public Nullable<System.DateTime> ngayBatDau { get; set; }
        public Nullable<System.DateTime> ngayHetHan { get; set; }
    }
}
