//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThienLongBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamDo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThamDo()
        {
            this.ChiTietThamDoes = new HashSet<ChiTietThamDo>();
        }
    
        public int maCH { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public string noiDungThamDo { get; set; }
        public Nullable<int> TongSoBinhChon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThamDo> ChiTietThamDoes { get; set; }
    }
}
