//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThienLongBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VietSach
    {
        public int maTG { get; set; }
        public int maSach { get; set; }
        public string vaiTro { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
